#!/bin/bash

# Get Volume
get_volume() {
  echo `amixer get Master | tail -n1 | awk -F ' ' '{print $5}' | tr -d '[]%'`
}

# Is mute
get_icon() {
	status=`amixer get Master | tail -n1 | grep -wo 'on'`

	if [[ "$status" == "on" ]]; then
    echo "󰕾"
	else
		echo "󰝟"
	fi
}

# Increase Volume
set_volume() {
  amixer -Mq set Master,0 $1% unmute
}

# Toggle Mute
toggle_mute() {
  amixer set Master toggle
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--icon" ]]; then
	get_icon
elif [[ "$1" == "--set" ]]; then
	set_volume "$2"
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
else
	get_volume
fi 
